version: '3.7'

services:
    php:
        container_name: php
        image: php:7.2-fpm
        restart: always
        volumes:
            - ./app:/www:rw
            - ./logs/php:/var/log/php:rw
        environment:
            TZ: 'Asia/Shanghai'

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        ports:
            - "8888:80"
        volumes:
            - ./app:/usr/share/nginx/html:rw
            - ./nginx/conf.d:/etc/nginx/conf.d:rw
            - ./logs/nginx:/var/log/nginx:rw
        environment:
            TZ: 'Asia/Shanghai'

    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        ports:
            - "8306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql:rw
            - ./logs/mysql:/var/log/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            TZ: 'Asia/Shanghai'

    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./mongodb/data:/data/db:rw
            - ./mongodb/backup:/data/backup:rw
        environment:
            TZ: 'Asia/Shanghai'