version: "3.7"

services:
    unblockneteasemusic:
        container_name: music
        image: nondanee/unblockneteasemusic
        restart: always
        ports:
            - "8080:8080"
        environment:
            NODE_ENV: "production"
            TZ: "$TZ"

    php:
        build: ./services/php
        container_name: php
        restart: always
        volumes:
            - ./app:/www:rw
            - ./logs/php:/var/log/php:rw
        environment:
            TZ: "$TZ"

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "12000-12010:12000-12010"
            - "13000-13010:13000-13010"
        volumes:
            - ./app:/usr/share/nginx/html:rw
            - ./nginx/conf.d:/etc/nginx/conf.d:rw
            - ./logs/nginx:/var/log/nginx:rw
        links:
            - php
        environment:
            TZ: "$TZ"

    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        ports:
            - "8306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql:rw
            - ./logs/mysql:/var/log/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            TZ: "$TZ"

    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./mongodb/data:/data/db:rw
            - ./mongodb/backup:/data/backup:rw
        environment:
            TZ: "$TZ"

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./redis/data:/data/:rw
            - ./redis/conf:/etc/redis:rw
            - ./logs/redis:/var/log/redis/:rw
        entrypoint: ["redis-server", "/etc/redis/redis.conf"]
        environment:
            TZ: "$TZ"

    gogs:
        container_name: gogs
        image: gogs/gogs
        restart: always
        ports:
            - "10022:22"
            - "10080:3000"
        volumes:
            - /gogs:/data
        links:
            - mysql
        environment:
            TZ: "$TZ"

    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:7.8.0
        restart: always
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            # 授权data目录权限
            - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
        environment:
            TZ: "$TZ"
            discovery.type: "single-node"

    kibana:
        container_name: kibana
        image: kibana:7.8.0
        restart: always
        ports:
            - "5601:5601"
        links:
            - elasticsearch
        volumes:
            - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
        environment:
            TZ: "$TZ"
            elasticsearch.hosts: "http://elasticsearch:9200"
        depends_on:
            - elasticsearch
